sudo pip3 install adafruit-extended-bus
sudo pip3 install adafruit-circuitpython-ahtx0
sudo pip3 install adafruit-circuitpython-bh1750
sudo pip3 install adafruit-circuitpython-bme280
sudo pip3 install adafruit-circuitpython-bme680
sudo pip3 install adafruit-circuitpython-sht31d
sudo pip3 install adafruit-circuitpython-sgp30
sudo pip3 install adafruit-circuitpython-sgp40
sudo pip3 install adafruit-circuitpython-scd30
sudo pip3 install adafruit-circuitpython-tsl2561
sudo pip3 install adafruit-circuitpython-ssd1305
sudo pip3 install adafruit-circuitpython-ssd1306
sudo pip3 install adafruit-circuitpython-ds1307
